//>>built
define("dojo/_base/declare dojo/_base/html dojo/_base/lang dojo/on dojo/Evented dojo/aspect dojo/mouse dojo/topic dojo/query ./Mover dojo/dnd/move dijit/_WidgetBase jimu/dijit/Message jimu/utils dojo/NodeList-dom dojo/NodeList-manipulate".split(" "),function(l,b,c,d,m,g,f,e,n,p,q,r,h,k){return l([r,m],{type:"",label:"",isMoving:!1,isMouseDown:!1,postCreate:function(){this.inherited(arguments);"addBtn"===this.type?(this.label="addBtn",this.createAddBtn()):"empty"===this.type?(this.label="empty",this.createEmptyNode()):
("widget"===this.type?this.createWidgetNode():this.createGroupNode(),"poolWidgets"===this.listName&&(this.dnd=new q.boxConstrainedMoveable(this.domNode,{handle:this.boxNode,box:this.parentBox,within:!0,delay:5,mover:p}),this.bindMoveEvent()));b.addClass(this.domNode,"moveable");b.setStyle(this.domNode,{width:this.w+"px",height:this.h+"px"})},bindMoveEvent:function(){g.after(this.dnd,"onMoveStart",c.hitch(this,function(){this.isMoving=!0}),!0);g.after(this.dnd,"onMoveStop",c.hitch(this,function(){this.isMoving=
!1}),!0)},_createWidgetIconNode:function(){var a=k.processUrlInAppConfig(this.setting.icon);this.iconNode=b.create("img",{"class":"icon",src:a,style:{width:"40px",height:"40px",margin:(this.w-40)/2+"px"}},this.boxNode)},_createPlaceholderNode:function(){this.placeholderNode=b.create("div",{"class":"placehoder",style:{width:"40px",height:"40px",margin:(this.w-40)/2+"px"}},this.boxNode);b.create("div",{"class":"placehoder-inner",innerHTML:this.setting.placeholderIndex,style:{width:"24px",height:"24px",
lineHeight:"24px",borderRadius:"12px",margin:"7px"}},this.placeholderNode)},createWidgetNode:function(){b.addClass(this.domNode,"widget-node");this.boxNode=b.create("div",{"class":"box",style:{width:this.w+"px",height:this.w+"px"}},this.domNode);this.setting.uri?this._createWidgetIconNode():this._createPlaceholderNode();this.label=this.setting.label?this.setting.label:this.nls.defaultWidgetLabel;this.name=this.setting.name?this.setting.name:this.nls.defaultWidgetLabel;this.labelNode=b.create("div",
{"class":"label",innerHTML:this.label,title:this.label},this.domNode);!1===this.setting.visible&&b.addClass(this.domNode,"hide");this.own(d(this.boxNode,f.enter,c.hitch(this,function(){e.publish("actionTriggered",{elementId:this.setting.id,action:"highLight"});this.setting.uri&&(this.editNode&&(b.destroy(this.editNode),this.editNode=null),this.dropNode&&(b.destroy(this.dropNode),this.dropNode=null),this.switchNode&&(b.destroy(this.switchNode),this.switchNode=null),this.editNode=this._createEditNode(),
this.own(d(this.editNode,"click",c.hitch(this,function(a){a.stopPropagation();e.publish("editWidget",this.setting)}))),!1===this.setting.inPanel?(this.switchNode=this._createSwitchNode(),this.own(d(this.switchNode,"click",c.hitch(this,function(a){a.stopPropagation();a=c.clone(this.setting);!1===a.visible?(a.visible=!0,b.removeClass(this.domNode,"hide")):(a.visible=!1,b.addClass(this.domNode,"hide"));e.publish("widgetChanged",a)})))):(this.dropNode=this._createDropNode(),this.own(d(this.dropNode,"click",
c.hitch(this,function(a){a.stopPropagation();var d=new h({message:this.nls.dropWidgetMessage,buttons:[{label:this.nls.ok,onClick:c.hitch(this,function(){"poolWidgets"===this.listName?console.log("list name poolWidgets"):(this.setting.uri="",this.setting.label=this.nls.defaultWidgetLabel,this.setting.name=void 0,this.setting.placeholderIndex="?",this.setting.config=void 0,this.label=this.nls.defaultWidgetLabel,this.labelNode.innerHTML=this.label,b.destroy(this.iconNode),this._createPlaceholderNode());
this.emit("removeNode");d.close()})},{label:this.nls.cancel}]})})))))})));this.own(d(this.boxNode,f.leave,c.hitch(this,function(){e.publish("actionTriggered",{elementId:this.setting.id,action:"removeHighLight"});this.editNode&&b.destroy(this.editNode);this.dropNode&&b.destroy(this.dropNode);this.switchNode&&b.destroy(this.switchNode)})))},createGroupNode:function(){b.addClass(this.domNode,"group-node");this.boxNode=b.create("div",{"class":"box",style:{width:this.w+"px",height:this.w+"px"}},this.domNode);
this.label=this.setting.label?this.setting.label:"Group";this.name=this.setting.name?this.setting.name:"Group";this.labelNode=b.create("div",{"class":"label",innerHTML:this.setting.label,title:this.setting.label},this.domNode);this._createSmallWidgets();this.own(d(this.boxNode,f.enter,c.hitch(this,function(){e.publish("actionTriggered",{elementId:this.setting.id,action:"highLight"});this.editNode=this._createEditNode();this.own(d(this.editNode,"click",c.hitch(this,function(a){a.stopPropagation();
e.publish("editGroup",this,this.setting)})));this.own(d(this.editNode,"mousedown",function(a){a.stopPropagation()}));this.own(d(this.editNode,"mouseup",function(a){a.stopPropagation()}));"poolWidgets"===this.listName&&(this.dropNode=this._createDropNode(),this.own(d(this.dropNode,"click",c.hitch(this,function(a){var b=new h({message:this.nls.dropGroupMessage,buttons:[{label:this.nls.ok,onClick:c.hitch(this,function(){this.emit("removeNode");b.close()})},{label:this.nls.cancel}]});a.stopPropagation()}))),
this.own(d(this.dropNode,"mousedown",function(a){a.stopPropagation()})),this.own(d(this.dropNode,"mouseup",function(a){a.stopPropagation()})))})));this.own(d(this.boxNode,f.leave,c.hitch(this,function(){e.publish("actionTriggered",{elementId:this.setting.id,action:"removeHighLight"});this.editNode&&b.destroy(this.editNode);this.dropNode&&b.destroy(this.dropNode)})));this.own(d(this.boxNode,"click",c.hitch(this,function(a){a.preventDefault();a.stopPropagation();"open"===this.status?this.closeGroup():
this.openGroup()})))},closeGroup:function(){this.status="close"},openGroup:function(){this.status="open"},createAddBtn:function(){b.addClass(this.domNode,"add-widget-node");var a=b.create("div",{"class":"box",style:{width:this.w+"px",height:this.w+"px"}},this.domNode);b.create("img",{src:this.folderUrl+"css/images/add_widget.png"},a);b.create("div",{"class":"label",title:this.nls.addWidget,innerHTML:this.nls.addWidget},a)},createEmptyNode:function(){b.addClass(this.domNode,"empty-node");b.create("div",
{"class":"box",style:{width:this.w+"px",height:this.w+"px"}},this.domNode)},_createEditNode:function(){var a={bottom:"4px",width:"25px",height:"25px"};a[window.isRTL?"left":"right"]="4px";return b.create("div",{"class":"edit-btn",style:a,title:this.nls.configureWidget},this.boxNode)},_createDropNode:function(){var a={top:"3px",width:"10px",height:"10px"};a[window.isRTL?"left":"right"]="3px";return b.create("div",{"class":"drop-btn",style:a,title:this.nls.removeWidget},this.boxNode)},_createSwitchNode:function(){var a=
b.hasClass(this.domNode,"hide")?this.nls.showWidget:this.nls.hideWidget,c={top:"3px",width:"15px",height:"10px"};c[window.isRTL?"left":"right"]="3px";return b.create("div",{"class":"switch-btn",style:c,title:a},this.boxNode)},_createSmallWidgets:function(){n(".small",this.boxNode).remove();var a=[],b=!1;4<this.setting.widgets.length?(a=this.setting.widgets.slice(0,3),b=!0):(a=this.setting.widgets,b=!1);a.forEach(c.hitch(this,function(a){this._createSmallWidget(a)}));b&&this._createSmallMore()},_createSmallWidget:function(a){var c;
c=b.create("div",{"class":"small small-widget","data-wid":a.id,style:{width:"20px",height:"20px",marginLeft:(this.w-40)/3+"px",marginTop:(this.w-40)/3+"px"}},this.boxNode);var d=a.icon;if(a.icon.startWith("widgets")||a.icon.startWith("configs")||a.icon.startWith("themes"))d=require(k.getRequireConfig()).toUrl(a.icon);b.create("img",{src:d,style:{width:"20px",height:"20px"}},c);return c},_createSmallMore:function(){var a;a=b.create("div",{"class":"small small-more",style:{width:"20px",height:"20px",
marginLeft:(this.w-40)/3+"px",marginTop:(this.w-40)/3+"px"}},this.boxNode);b.create("img",{src:"builder/images/more_widget.png",style:{width:"20px"}},a);return a},addWidget:function(a){"group"!==this.type?console.log("can not add widget to widget"):(this.setting.widgets.push(a.setting),this._createSmallWidgets())},updateSmallWidgets:function(){this._createSmallWidgets()},destroy:function(){this.margin&&this.margin.destroy();this.inherited(arguments)}})});