//>>built
define("dojo/_base/declare dojo/_base/lang dojo/_base/html dojo/_base/array dojo/topic dojo/aspect dojo/on dojo/query dojo/NodeList-dom dijit/_WidgetBase ./MoveableNode ./LinkList".split(" "),function(p,f,e,r,g,h,s,m,w,q,t,u){function n(a){var b={};isFinite(a.l)&&(b.left=a.l+"px");isFinite(a.t)&&(b.top=a.t+"px");isFinite(a.w)&&(b.width=a.w+"px");isFinite(a.h)&&(b.height=a.h+"px");return b}var k,v=p([q],{postCreate:function(){this.inherited(arguments);this.domNode=e.create("div",{"class":"node-margin"});
this.type="addBtn"===this.node.type?"addMargin":"margin"}});return p([q],{postCreate:function(){this.nodeList=new u({name:this.name});this.own(g.subscribe("widgetChoosePageOk",f.hitch(this,this._onWidgetChoosePageOk)));this.own(g.subscribe("widgetSettingPageOk",f.hitch(this,this._onWidgetSettingPageOk)))},startup:function(){this.inherited(arguments);var a=e.getContentBox(this.domNode);this.position=e.position(this.domNode);k=Math.floor(a.w/89);this.settings&&this.initNodes()},setSettings:function(a){this.settings=
a;this.initNodes()},setAppConfig:function(a){this.appConfig=a},addWidget:function(a){a=this.createMoveableNode("widget",a);this.nodeList.insertNode(a);this.placeNodes()},createMoveableNode:function(a,b){var c=e.getContentBox(this.domNode);c.h=Infinity;var d=new t({type:a,w:74,h:118,setting:b,listName:this.name,parentBox:c,nls:this.nls,folderUrl:this.folderUrl});e.place(d.domNode,this.domNode);d.startup();this.bindMoveEvent(d);"group"===a&&(h.after(d,"openGroup",f.hitch(this,this.openGroup,d)),h.after(d,
"closeGroup",f.hitch(this,this.closeGroup,d)));d.on("removeNode",f.hitch(this,function(){"poolWidgets"===this.name?(d.gnode?(this.nodeList.removeNode(d),this._reopenGroup()):this.nodeList.removeNode(d),this.placeNodes(),this.publishPoolChangeEvent()):g.publish("widgetChanged",d.setting)}));this.createMarginNode(d);this.own(s(d.domNode,"click",f.hitch(this,function(){("addBtn"===a||"widget"===a&&!b.uri)&&g.publish("chooseWidget",d,this.name)})));return d},openGroup:function(a){var b,c,d,e,g,h,l;this.openedGNode&&
this.openedGNode!==a&&this.openedGNode.closeGroup(this.openedGNode);b=a.setting.widgets;g=this.getNodePosition(this.nodeList.getNodeIndex(a)).r;h=Math.ceil(b.length/k);c=g*k+1;d=this.nodeList.getNodeByIndex(c);for(e=this.nodeList.getCount()+1;e<c;e++)l=this.createMoveableNode("empty"),l.gnode=a,this.nodeList.insertNode(l,d);this.openedGNode=a;this.openedGNode.panelRow=g+1;this.createGroupPanel(g+1,h);b.forEach(f.hitch(this,function(b){b=this.createMoveableNode("widget",b);b.gnode=a;this.nodeList.insertNode(b,
d)}));b=k*h-b.length;for(e=0;e<b;e++)l=this.createMoveableNode("empty"),l.gnode=a,this.nodeList.insertNode(l,d);this.placeNodes()},createGroupPanel:function(a,b){this.groupPanel=e.create("div",{"class":"widget-group-panel",style:n({l:5,t:118*(a-1)-10,h:118*b+0*(b-1),w:89*k-15+20})},this.domNode);e.create("div",{"class":"group-triangle",style:{left:89*((this.openedGNode.pos.c-1)%k)+37+"px"}},this.groupPanel);this.groupPanel.type="panel"},closeGroup:function(a){var b=[];a.setting.widgets=[];this.nodeList.visitNodes(f.hitch(this,
function(c){c.gnode===a&&("empty"!==c.type&&a.setting.widgets.push(c.setting),b.push(c))}));b.forEach(f.hitch(this,function(a){this.nodeList.removeNode(a)}));0===a.setting.widgets.length?this.nodeList.removeNode(a):a.updateSmallWidgets();this.placeNodes();e.destroy(this.groupPanel);this.openedGNode=null},initNodes:function(){this.destroyShadowNode();var a=this.settings,a="widgetOnScreen"===this.name?a.sort(firstBy(function(a,b){return a.inPanel!==b.inPanel?a.inPanel-b.inPanel:0}).thenBy(function(a,
b){return a.uri&&!b.uri?-1:!a.uri&&b.uri?1:0}).thenBy(function(a,b){return a.uri&&b.uri?a.label.localeCompare(b.label):!a.uri&&!b.uri?a.placeholderIndex-b.placeholderIndex:0})):a.sort(function(a,b){return a.index-b.index}),b;this.openedGNode&&(b=this.openedGNode.label,this.closeGroup(this.openedGNode));this.nodeList.destroyAllNodes();"poolWidgets"===this.name&&(this.addBtn=this.createMoveableNode("addBtn"),this.nodeList.insertNode(this.addBtn));a.forEach(f.hitch(this,function(a){var b;a.widgets?0<
a.widgets.length?b=this.createMoveableNode("group",a):console.log("empty group"):b=this.createMoveableNode("widget",a);b&&this.nodeList.insertNode(b)}));this.nodeList.insertNode(this.createMoveableNode("empty"));this.placeNodes();if(b&&(a=this.nodeList.getNodeByLabel(b)))this.openGroup(a),a.status="open"},_removeActive:function(){m(".node-margin-active",this.domNode).removeClass("node-margin-active");m(".empty-node-active",this.domNode).removeClass("empty-node-active");m(".node-active",this.domNode).removeClass("node-active")},
bindMoveEvent:function(a){"addBtn"!==a.type&&a.dnd&&(h.after(a.dnd,"onMove",f.hitch(this,function(b,c,d){b=this.getMousePosition(d);this.mouseNode=this.getNodeByMousePosition(a,b);this._removeActive();this.mouseNode&&"margin"===this.mouseNode.type?e.addClass(this.mouseNode.domNode,"node-margin-active"):this.mouseNode&&"empty"===this.mouseNode.type?e.addClass(this.mouseNode.domNode,"empty-node-active"):this.mouseNode&&("group"===this.mouseNode.type||"widget"===this.mouseNode.type)&&e.addClass(this.mouseNode.domNode,
"node-active")}),!0),h.after(a.dnd,"onMoveStart",f.hitch(this,function(){this.destroyShadowNode();this.createShadowNode(a);e.setStyle(a.boxNode,"cursor","move")}),!0),h.after(a.dnd,"onMoveStop",f.hitch(this,this._onMoveStop,a),!0))},_onMoveStop:function(a){var b=!1;e.setStyle(a.boxNode,"cursor","pointer");this.mouseNode&&(a===this.mouseNode?console.log("move to the same node"):"margin"===this.mouseNode.type?(this.moveNodeToMargin(a,this.mouseNode),b=!0):"empty"===this.mouseNode.type?this.mouseNode.gnode&&
"group"===a.type?console.log("not allow move group to opened group, revert"):(this.moveNodeToEmpty(a,this.mouseNode),b=!0):"group"===this.mouseNode.type?"group"===a.type?console.log("not allow move group to closed group, revert"):"open"===this.mouseNode.status?console.log("please put widget into the opened group panel"):a.gnode&&a.gnode===this.mouseNode?console.log("the moving widget is already in the group"):(this.moveWidgetToGroup(a,this.mouseNode),b=!0):"widget"===this.mouseNode.type&&("group"===
a.type?console.log("not allow move group to widget, revert"):a.gnode||this.mouseNode.gnode?console.log("can not nest group"):(this.moveWidgetToWidget(a,this.mouseNode),b=!0)),this._reopenGroup());this.destroyShadowNode();b&&this.publishPoolChangeEvent();this.placeNodes()},_reopenGroup:function(){if(this.openedGNode){var a=this.openedGNode;this.closeGroup(a);this.nodeList.isExist(a)&&this.openGroup(a)}},getNodePosition:function(a){var b={},c;c=Math.ceil(a/k);a%=k;0===a&&(a=k);b.t=118*(c-1);b.l=89*
(a-1)+15;b.w=74;b.h=118;b.r=c;b.c=a;return b},getMarginNodePosition:function(a){var b={};a=a.pos;b.l=a.l-7.5-2.5;b.t=a.t;b.w=5;b.h=118;return b},createMarginNode:function(a){var b=new v({label:a.label,node:a});e.place(b.domNode,this.domNode);return a.margin=b},getMousePosition:function(a){return{x:a.pageX-this.position.x,y:a.pageY-this.position.y+this.domNode.scrollTop}},moveNodeToMargin:function(a,b){var c=this.getNodeByMarginNode(b);console.log("moveNodeToMargin");m(".node-margin-active",this.domNode).removeClass("node-margin-active");
c.gnode&&!a.gnode?a.gnode=c.gnode:!c.gnode&&a.gnode&&(a.gnode=null);this.nodeList.moveNode(a,c)},moveNodeToEmpty:function(a,b){m(".empty-node-active",this.domNode).removeClass("empty-node-active");b.gnode&&!a.gnode?a.gnode=b.gnode:!b.gnode&&a.gnode&&(a.gnode=null);this.nodeList.moveNode(a,b)},getNodeByMarginNode:function(a){var b;this.nodeList.visitNodes(function(c){c.margin===a&&(b=c)});return b},placeNodes:function(){var a,b;this.nodeList.visitNodes(f.hitch(this,function(c,d){a=this.getNodePosition(d);
c.pos=a;e.setStyle(c.domNode,n(a));b=this.getMarginNodePosition(c);c.margin.pos=b;e.setStyle(c.margin.domNode,n(b))}));this.nodeList.printNodeList()},moveWidgetToGroup:function(a,b){b.addWidget(a);this.nodeList.removeNode(a)},moveWidgetToWidget:function(a,b){var c;c=this.createMoveableNode("group",{label:this._getGroupLabel(),widgets:[a.setting,b.setting]});this.nodeList.insertNode(c,b);this.nodeList.removeNode(a);this.nodeList.removeNode(b)},createShadowNode:function(a){this.shadowNode=e.create("div",
{"class":"node-shadow",style:n(e.getMarginBox(a.domNode))},this.domNode)},destroyShadowNode:function(){this.shadowNode&&e.destroy(this.shadowNode)},getNodeByMousePosition:function(a,b){var c;this.nodeList.visitNodes(function(d){if("addBtn"!==d.type){if(b.x>d.pos.l+10&&(b.x<d.pos.l+d.pos.w-10&&b.y>d.pos.t+10&&b.y<d.pos.t+d.pos.h-10)&&d!==a)return c=d,!0;if(b.x>d.margin.pos.l&&(b.x<d.margin.pos.l+d.margin.pos.w&&b.y>d.margin.pos.t&&b.y<d.margin.pos.t+d.margin.pos.h)&&d.margin!==a)return c=d.margin,
!0}});return c},_getGroupLabel:function(){var a=-1;this.appConfig.visitElement(f.hitch(this,function(b){if(b.widgets)if(b.label===this.nls.newGroup)a=0;else if(b.label.startWith(this.nls.newGroup)){var c=b.label.lastIndexOf("_");-1<c&&(b=parseInt(b.label.substr(c+1,b.label.length),10),a=Math.max(a,b))}}));return-1===a?this.nls.newGroup:this.nls.newGroup+"_"+(a+1)},_onWidgetChoosePageOk:function(a,b){if(b.listName===this.name)if(1===a.length){var c;"addBtn"===b.type?c=a[0]:(c=f.clone(b.setting),f.mixin(c,
a[0]));g.publish("editWidget",c)}else"addBtn"===b.type&&(r.forEach(a,function(a){this.addWidget(a)},this),this.publishPoolChangeEvent())},_onWidgetSettingPageOk:function(a){this.opened&&(a.id?g.publish("widgetChanged",a):"poolWidgets"===this.name&&(this.addWidget(a),this.publishPoolChangeEvent()))},publishPoolChangeEvent:function(){var a=[],b=[];this.nodeList.visitNodes(function(c,d){"widget"===c.type&&!c.gnode?(c.setting.index=d,b.push(c.setting)):"group"===c.type&&(c.setting.index=d,a.push(c.setting))});
g.publish("widgetPoolChanged",{widgets:b,groups:a})}})});