define(
   ({
    "tabs_section_Label": "Välilehdet",
    "addTab": "Lisää välilehti",
    "layerName": "Karttataso",
    "layerType": "Analyysityyppi",
    "layerLabel": "Label",
    "actions": "Toimet",
    "closest": "Lähin kohde",
    "proximity": "Läheisyys",
    "summary": "Summary",
    "select_lbl": "-- Valitse --",
    "general_setting_Label": "Yleiset asetukset",
    "units_text_lbl": "Etäisyyden yksiköt",
    "miles": "Mailia",
    "kilometers": "Kilometriä",
    "feet": "Jalka",
    "meters": "Metriä",
    "yards": "Jaardia",
    "nauticalMiles": "Meripeninkulmaa",
    "maximum_distance_lbl": "Lähimmän kohteen enimmäisetäisyys",
    "buffer_text_lbl": "Puskurin nimiö",
    "buffer_lbl": "Puskurin etäisyys",
    "buffer_max_lbl": "Puskurin enimmäisetäisyys",
    "buffer_min_lbl": "Puskurin vähimmäisetäisyys",
    "routing_checkBox": "Ota reititys käyttöön",
    "weather_Label": "Sääolosuhteet",
    "weather_checkBox": "Sisällytä säätiedot",
    "selectLayers": "Valitse sääkarttatasot",
    "currentlySelectedLayer": "Tällä hetkellä valitut sääkarttatasot",
    "missingTabLabel": "Vähintään yhdestä välilehdestä puuttuu nimiö",
    "cancel": "Peruuta",
    "ok": "OK",
    "missingLayerInWebMap": "Toiminnallisia karttatasoja ei löytynyt."
  })
);
