define(
   ({
    selectAnalysisTools:"Velg analyseverktøy som skal brukes i miniprogrammet.",
    selected: "valgte",
    name: "Navn",
    graphicalDisplay:"Grafisk visning",
    usage: "Bruk",
    settings: "Innstillinger",
    toolSetting: "Angi verktøydetaljer",
    toolLabel: "Visningsnavnet for verktøyet",
    showHelpTip: "Vis hjelpekoblinger i miniprogrammet",
    showCurrentMapExtent: "Vis alternativ for å bruke det gjeldende kartet",
    showCredits: "Vis alternativet <b>Vis credits</b>",
    saveAsFeatureService: "Lagre resultatet i brukerens konto",
    showReadyToUseLayers: "Vis bruksklare lag fra det levende verdensatlaset på ArcGIS Online",
    toolNotAvailable: "Dette verktøyet er ikke tilgjengelig fordi kartet ikke inneholder et eller flere nødvendige geoobjektslag.",
    aggregatePoints:"Samle punkter",
    aggregatePointsUsage:"Samle punkter i polygoner der punktene befinner seg.",
    calculateDensity:"Beregn tetthet",
    calculateDensityUsage:"Lag et tetthetskart fra punkt- eller linjegeoobjekter ved å spre kjente mengder av et fenomen (vises som attributter for punktene eller linjene) over kartet.",
    connectOriginsToDestinations: "Koble startpunkter til destinasjoner",
    connectOriginsToDestinationsUsage: "Beregn reisetiden eller avstanden mellom to punkter.",
    createBuffers:"Opprett buffere",
    createBuffersUsage:"Opprett bufferpolygoner fra inndatageoobjektene.",
    createDriveTimeAreas:"Opprett kjøretidsområder",
    createDriveTimeAreasUsage:"Opprett kjøretidspolygoner (eller kjøreavstand) rundt inndatapunktene for angitte kjøretidsverdier.",
    createViewshed:"Create Viewshed",
    createViewshedUsage:"Oppretter områder som er synlige basert på lokasjonene du angir.",
    createWatersheds:"Create Watersheds",
    createWatershedsUsage:"Oppretter nedbørsfeltområder basert på lokasjonene du oppgir.",
    deriveNewLocations:"Utled nye plasseringer",
    deriveNewLocationsUsage:"Utled nye geoobjekter fra inndatalagene som oppfyller en spørring du angir",
    dissolveBoundaries:"Visk ut grenser",
    dissolveBoundariesUsage:"Løs opp polygoner som overlapper eller deler en felles grense.",
    enrichLayer:"Suppleringsdata",
    enrichLayerUsage:"Berik inndatageoobjekter med fakta om mennesker, steder og bedrifter i nærliggende områder.",
    extractData:"Ekstraher data",
    extractDataDesc:"Trekk ut data fra ett eller flere lag med en gitt utstrekning",
    findExistingLocations:"Finn eksisterende plasseringer",
    findExistingLocationsUsage:"Velg geoobjekter i inndatalaget som oppfyller et attributt og/eller geografisk spørring du angir",
    findHotSpots:"Finn hotspots",
    findHotSpotsUsage:"Finn statistisk signifikante klynger med inndatageoobjekter eller høye/lave verdier.",
    findNearest:"Finn nærmeste",
    findNearestUsage:"For hvert geoobjekt i et inndatalag finner du dets nærmeste geoobjekt i et annet lag",
    findSimilarLocations:"Finn lignende lokasjoner",
    findSimilarLocationsUsage:"Mål likheten mellom kandidatlokasjoner og to eller flere referanselokasjoner.",
    interpolatePoints:"Interpoler punkter",
    interpolatePointsUsage:"Forutsi verdier på nye lokasjoner basert på målinger fra en samling punkter.",
    mergeLayers:"Slå sammen lag",
    mergeLayersUsage:"Slå sammen geoobjekter fra flere lag til et nytt lag.",
    overlayLayers:"Legg lag oppå",
    overlayLayersUsage:"Kombiner flere lag til ett enkelt lag der informasjonen fra de opprinnelige lagene beholdes.",
    planRoutes:"Planlegg ruter",
    planRoutesUsage:"Finn ut hvordan du effektivt fordeler oppgaver i en mobil arbeidsstyrke.",
    summarizeNearby:"Summer nærliggende",
    summarizeNearbyUsage:"For hvert geoobjekt i et inndatalaget summerer du data innenfor en avstand fra geoobjekter på et annet lag.",
    summarizeWithin:"Summer innenfor",
    summarizeWithinUsage:"For hvert polygon i et lagt med inndatapolygoner summerer du data som befinner seg i det fra geoobjekter i et annet lag.",
    traceDownstream:"Spor medstrøm",
    traceDownstreamUsage:"Finner strømningslinjene i nedstrøms retning fra lokasjonene du oppgir."
  })
);
