define(
	 ({
		queries: "查詢任務",
		addNew: "新增新坐標",
		setSource: "設置",
		setDataSource: "設定資料來源",
		name: "名稱",
		querySource: "資料來源",
		queryName: "任務名稱",
		queryDefinition: "篩選器定義",
		resultsSetting: "結果設定",
		symbolSetting: "符號設定",
		resultSettingTip: "定義輸出結果的顯示內容和顯示方式。",
		resultItemTitle: "結果項目標題",
		resultItemContent: "結果項目內容",
		fieldsSetTip: "檢查您希望顯示的欄位。選擇要更新別名、進行排序和格式化的欄位。",
		addField: "新增欄位",
		visibility: "能見度",
		alias: "別名",
		specialType: "特殊類型",
		actions: "操作",
		none: "無",
		link: "連結",
		image: "圖片",
		noField: "無欄位",
		operationalLayerTip: "將結果新增為業務圖層",
		setLayerSymbolTip: "設定查詢結果的符號： ",
		setSelectedSymbolTip: "設定所選圖徵的符號。",
		notUseFilter: "不使用篩選器",
		setSourceTip: "請設定查詢來源。",
		setFilterTip: "請正確設定篩選器。",
		ok: "確定",
		cancel: "取消",
		noFilterTip: "在未定義篩選表達式的情況下，此查詢任務會列出指定資料來源的所有圖徵。",
    relationships: "關係表",
    addRelationshipLayer: "新增新關係",
    relatedTo: "關聯對象",
    selectOption: "請選擇..",
    resultItemSorting: "結果項目排序",
    field: "欄位",
    sortingOrder: "順序",
    configureFieldsTip: "請配置對查詢結果進行排序所依據的欄位。",
    setSortingFields: "設定排序欄位",
    ascending: "昇冪",
    descending: "降冪",
    sortBy: "排序方式",
    thenBy: "次排序方式"
  })
);
