define(
   ({
    "tabs_section_Label": "tabbladen",
    "addTab": "Tabblad toevoegen",
    "layerName": "Kaartlaag",
    "layerType": "Analysetype",
    "layerLabel": "Label",
    "actions": "Acties",
    "closest": "Dichtstbijzijnde object",
    "proximity": "Nabijheid",
    "summary": "Samenvatting",
    "select_lbl": "-- Selecteren --",
    "general_setting_Label": "Algemene instellingen",
    "units_text_lbl": "Afstandseenheden",
    "miles": "Mijl",
    "kilometers": "Kilometer",
    "feet": "Voet",
    "meters": "Meter",
    "yards": "Yard",
    "nauticalMiles": "Zeemijl",
    "maximum_distance_lbl": "Dichtstbijzijnde object maximale afstand",
    "buffer_text_lbl": "Bufferlabel",
    "buffer_lbl": "Bufferafstand",
    "buffer_max_lbl": "Maximale bufferafstand",
    "buffer_min_lbl": "Minimale bufferafstand",
    "routing_checkBox": "Routeren inschakelen",
    "weather_Label": "Weeropties",
    "weather_checkBox": "Weerberichten opnemen",
    "selectLayers": "Weerlagen selecteren",
    "currentlySelectedLayer": "Momenteel geselecteerde weerlagen",
    "missingTabLabel": "Er ontbreekt minstens één label in het tabblad",
    "cancel": "Annuleren",
    "ok": "OK",
    "missingLayerInWebMap": "Geen operationele lagen gevonden."
  })
);
