//>>built
define(["dojo/_base/declare","dojo/_base/lang","dojo/_base/array"],function(l,h,k){var g={},e=l([],{id:null,parentNode:null,keyString:null,absolutePath:null,childs:null,nodeType:null,templateField:null,jsonObject:null,level:null,label:null,isVisible:!1,constructor:function(a,b,c,d,e){var f;this.parentNode=b;this.keyString=c;this.childs=[];this.absolutePath=""===d?c:d+"_"+c;this.jsonObject=a;this.level=e;this.initId();this.initLabel();this.initTemplateField(a);if("object"!==typeof a||null===a)this.nodeType=
"leaf";else if(h.isArrayLike(a)){this.nodeType="array";for(b=0;b<a.length;b++)this.addChild(a[b],this.keyString+"["+b+"]",d,e)}else for(f in this.nodeType="normal",a)a.hasOwnProperty(f)&&"function"!==typeof a[f]&&this.addChild(a[f],f,this.absolutePath,e)},initId:function(){var a,b;a=this.absolutePath.search(/_widgets\[[0-9]+\]/);b=this.absolutePath.search(/_groups\[[0-9]+\]/);-1!==a||-1!==b?-1!==this.absolutePath.search(/_widgets\[[0-9]+\]$/)||-1!==this.absolutePath.search(/_groups\[[0-9]+\]$/)?this.id=
this.parentNode.id+"["+this.jsonObject.id+"]":h.isArrayLike(this.parentNode.jsonObject)?this.id=this.parentNode.parentNode.id+"_"+this.keyString:this.id=this.parentNode.id+"_"+this.keyString:this.id=this.absolutePath},initLabel:function(){this.label=this.keyString;if(-1!==this.absolutePath.search(/widgets\[[0-9]+\]$/)||-1!==this.absolutePath.search(/groups\[[0-9]+\]$/))this.label=this.jsonObject.label},initTemplateField:function(a){this.templateField=e.getDefaultTemplateField(this.absolutePath,typeof a,
this.label);e.setDefaultValue(this.absolutePath,a,this.id)},getTemplateFieldDefaultValue:function(){return this.templateField.defaultValue},getTemplateField:function(){var a={type:this.templateField.type,fieldName:this.id,label:this.templateField.label,tooltip:this.templateField.tooltip};"leaf"!==this.nodeType&&(a.fieldName+="--");switch(a.type){case "string":a.stringFieldOption=this.templateField.stringFieldOption;a.placeHolder=this.templateField.placeHolder;break;case "number":a.constraints=this.templateField.constraints;
break;case "options":a.options=this.templateField.options}a.id=this.id;a.fieldPath=this.absolutePath;return a},setTemplateField:function(a){this.templateField.type=a.type;this.templateField.label=a.label;this.templateField.tooltip=a.tooltip;"leaf"!==this.nodeType&&(this.templateField.fieldName=this.templateField.fieldName.slice(0,this.templateField.fieldName.length-2));switch(this.templateField.type){case "string":this.templateField.stringFieldOption=a.stringFieldOption;this.templateField.placeHolder=
a.placeHolder;break;case "number":this.templateField.constraints=a.constraints;break;case "options":this.templateField.options=a.options}return a},addChild:function(a,b,c,d){a=new e(a,this,b,c,d+1);this.childs.push(a);return a},isLeaf:function(){var a=!1;this.childs&&0<this.childs.length&&(a=!0);return a},findNode:function(a){var b=[],c,d,e;a.split("_").forEach(function(a){var c=a.search(/\[[0-9]+\]/);-1!==c&&b.push(a.slice(0,c));b.push(a)});d=this;if(d.keyString!==b[0])return null;for(a=1;a<b.length;a++){e=
d.childs.length;for(c=0;c<e;c++)if(d.childs[c].keyString===b[a]){d=d.childs[c];break}if(c===e)return null}return d},setVisible:function(){for(var a=this;a;)a.isVisible=!0,a=a.parentNode},findNodeById:function(a){var b=null;this.traversal(function(c){if(c.id===a)return b=c,!0});return b},traversal:function(a){if(a(this))return!0;for(var b=0;b<this.childs.length;b++)if(this.childs[b].traversal(a))return!0},deserialize:function(a){a&&k.forEach(a.configurationSettings,function(a){k.forEach(a.fields,function(a){this.findNode(a.fieldName).setTemplateField(a)},
this)},this)}});e.getDefaultValue=function(a){return g[a]};e.setDefaultValue=function(a,b,c){var d=null,d=b;"app_portalUrl"===a||"app_map_itemId"===a?d=null:"app_title"===a?d="":"app_subtitle"===a?d="":"object"===typeof b&&(d=!1);g[c]=d};e.defaultValueExisted=function(a){return void 0===g[a]?!1:!0};e.getDefaultTemplateField=function(a,b,c){a="string";switch(b){case "number":a="number";break;case "boolean":a="boolean";break;case "object":a="boolean",c="disable"}return{type:a,label:c,tooltip:"",stringFieldOption:"textbox",
placeHolder:c,constraints:{min:0,max:100,places:0},options:[{label:"label1",value:"value1"},{label:"label2",value:"value2"}]}};return e});